"""Engine interfaces."""

from __future__ import annotations

from typing import Generator, Protocol


class InferenceEngine(Protocol):
    def is_available(self) -> bool: ...
    def list_models(self) -> list: ...
    def chat(self, messages: list, stream: bool = False) -> str: ...
    def stream_chat(self, messages: list) -> Generator[str, None, None]: ...
